name: Build Android APK (Auto Versioning)

on:
  workflow_dispatch: # Mengaktifkan kembali tombol rakit manual
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mengambil Kode Aplikasi
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Menghitung Version Code
        id: version_code
        run: |
          CODE=$(git rev-list --count HEAD)
          echo "VERSION_CODE=$CODE" >> $GITHUB_ENV

      - name: Mengambil Version Name
        id: version_name
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            NAME=${GITHUB_REF#refs/tags/v}
          else
            NAME="Manual-Build"
          fi
          echo "VERSION_NAME=$NAME" >> $GITHUB_ENV

      - name: Menyiapkan Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Memberi Izin Eksekusi Gradle
        run: chmod +x gradlew

      - name: Menyiapkan API Key Gemini
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
          echo "API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: Merakit APK Release
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.version.code=${{ env.VERSION_CODE }} \
            -Pandroid.injected.version.name="${{ env.VERSION_NAME }}"

      - name: Menyimpan File APK
        uses: actions/upload-artifact@v4
        with:
          name: DuitKu-${{ env.VERSION_NAME }}-APK
          path: app/build/outputs/apk/release/app-release.apk